#!/bin/sh
#
# ufetch-ubuntu - tiny system info for ubuntu

## INFO
#kernel part -sr
# user is already defined
host="$(hostname)"
os="Ubuntu 18.04.4 LTS on WSL"
kernel="ntoskrnl"
uptime="$(uptime -p | sed 's/up //')"
packages="$(dpkg -l | wc -l)"
shell="$(basename "$SHELL")"

## UI DETECTION

if [ -n "${DE}" ]; then
	ui="${DE}"
	uitype='DE'
elif [ -n "${WM}" ]; then
	ui="${WM}"
	uitype='WM'
elif [ -n "${XDG_CURRENT_DESKTOP}" ]; then
	ui="${XDG_CURRENT_DESKTOP}"
	uitype='DE'
elif [ -n "${DESKTOP_SESSION}" ]; then
	ui="${DESKTOP_SESSION}"
	uitype='DE'
elif [ -f "${HOME}/.xinitrc" ]; then
	ui="$(tail -n 1 "${HOME}/.xinitrc" | cut -d ' ' -f 2)"
	uitype='WM'
elif [ -f "${HOME}/.xsession" ]; then
	ui="$(tail -n 1 "${HOME}/.xsession" | cut -d ' ' -f 2)"
	uitype='WM'
else
	ui='dwm'
	uitype='UI'
fi

## DEFINE COLORS

# probably don't change these
if [ -x "$(command -v tput)" ]; then
	bold="$(tput bold)"
	black="$(tput setaf 0)"
	red="$(tput setaf 1)"
	green="$(tput setaf 2)"
	yellow="$(tput setaf 3)"
	blue="$(tput setaf 4)"
	magenta="$(tput setaf 5)"
	cyan="$(tput setaf 6)"
	white="$(tput setaf 7)"
	reset="$(tput sgr0)"
fi

# you can change these
lc="${reset}${bold}${yellow}"       # labels
nc="${reset}${bold}${yellow}"       # user and hostname
ic="${reset}"                       # info
c0="${reset}${yellow}"              # first color

## OUTPUT

cat <<EOF

${c0}           _   ${nc}${USER}${ic}@${nc}${host}${reset}
${c0}       ---(_)  ${lc}os:        ${ic}${os}${reset}
${c0}   _/  ---  \\  ${lc}kernel:    ${ic}${kernel}${reset} 
${c0}  (_) |   |    ${lc}uptime:    ${ic}${uptime}${reset}
${c0}    \\  --- _/  ${lc}pkgs:      ${ic}${packages}${reset} 
${c0}       ---(_)  ${lc}shell:     ${ic}${shell}${reset}
${c0}               ${lc}wm:        ${ic}${ui}${reset}

EOF
